import{useEffect,useMemo,useState}from"react";import{Clipboard,Files,History,Laptop,Link2,RefreshCw,Settings,ShieldCheck,Smartphone,Wifi}from"lucide-react";import{QRCodeSVG}from"qrcode.react";import{invoke}from"@tauri-apps/api/core";import{check}from"@tauri-apps/plugin-updater";import{relaunch}from"@tauri-apps/plugin-process";
type Pairing={device_id:string;device_name:string;host:string;port:number;nonce:string;expires_at:number};
const preview:Pairing={device_id:"desktop-preview",device_name:"This Windows PC",host:"192.168.1.8",port:47123,nonce:"preview",expires_at:0};
export default function App(){const[pairing,setPairing]=useState(preview);const[tab,setTab]=useState("pair");const[update,setUpdate]=useState("You're up to date");const payload=useMemo(()=>JSON.stringify({app:"ClipLink",version:1,...pairing}),[pairing]);useEffect(()=>{invoke<Pairing>("create_pairing").then(setPairing).catch(()=>{})},[]);async function checkUpdate(){setUpdate("Checking…");try{const u=await check();if(!u)return setUpdate("You're up to date");setUpdate(`Downloading ${u.version}…`);await u.downloadAndInstall();await relaunch()}catch{setUpdate("Release feed will activate when ClipLink is published")}}
return <div className="shell"><aside><div className="brand"><b><Link2/>ClipLink</b><span>Private device bridge</span></div><nav><button className={tab==="pair"?"active":""}onClick={()=>setTab("pair")}><Smartphone/>Pair device</button><button className={tab==="history"?"active":""}onClick={()=>setTab("history")}><History/>Clipboard</button><button className={tab==="files"?"active":""}onClick={()=>setTab("files")}><Files/>Files</button><button className={tab==="settings"?"active":""}onClick={()=>setTab("settings")}><Settings/>Settings</button></nav><div className="privacy"><ShieldCheck/><div><b>Local & encrypted</b><span>Your data stays on your devices.</span></div></div></aside><main><header><div><small>CLIPLINK DESKTOP</small><h1>{tab==="pair"?"Connect your phone":tab==="history"?"Clipboard history":tab==="files"?"File transfer":"Settings"}</h1></div><label><i/>Ready on local Wi-Fi</label></header>
{tab==="pair"&&<section className="grid"><div className="card"><em>1</em><h2>Scan to pair</h2><p>Open ClipLink on Android and scan this code. No account, internet, or cloud required.</p><div className="qr"><QRCodeSVG value={payload}size={190}/></div><button className="action"onClick={()=>invoke<Pairing>("create_pairing").then(setPairing)}><RefreshCw/>Refresh code</button></div><div className="card"><em>2</em><h2>Start copying</h2><p>Text and images copied on either device become available on the other.</p><div className="route"><div><Laptop/>This PC</div><span>••••••</span><div><Smartphone/>Android</div></div><div className="network"><Wifi/><div><b>{pairing.host}:{pairing.port}</b><span>Direct local connection</span></div></div></div></section>}
{tab==="history"&&<section className="card"><h2>Recent clipboard</h2><article><Clipboard/><div><b>Welcome to ClipLink — copied items appear here.</b><span>This PC · Just now</span></div></article></section>}
{tab==="files"&&<section className="card empty"><Files/><h2>Drop files here</h2><p>Transfer files and folders directly over local Wi-Fi.</p><button className="primary">Choose files</button></section>}
{tab==="settings"&&<section className="card setting"><div><h2>Automatic updates</h2><p>Receive signed ClipLink releases.</p></div><button className="action"onClick={checkUpdate}><RefreshCw/>Check now</button><p>{update}</p></section>}</main></div>}
